var mythicitems = [
    { name: "シュレリアの戦果", effect: "効果1", passive: "効果", mythicEffect: "ミシック効果1" ,money:"1000G", type: "mythic"},
    { name: "ムーンストーンの再生", effect: "効果2", passive: "", mythicEffect: "ミシック効果2" ,money:"1000G", type: "mythic"},
    { name: "ヘリアの残響", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "イーブンシュラウド", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "ソラリのロケット", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "レディアントヴァ―チュ", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "シャッタードクイーンクラウン", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "エバーフロスト", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "ロッドオブエイジス", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "アイスボーンガントレット", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "妖夢の霊剣", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "ドラクサーダスクブレード", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "赤月の刃", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "ライアンドリーの苦悶", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "ルーデンテンペスト", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "ナイトハーベスター", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "ヘクステックロケットベルト", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "リフトメーカー", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "グインソーレイジブレード", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "ゴアドリンカー", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "変幻自在のジャック＝ショー", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "心の鋼", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "ストライドブレイカー", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "ディヴァインサンダラー", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "トリニティフォース", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "ゲイルフォース", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "ナヴォリクイックブレード", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
    { name: "インフィニティエッジ", effect: "効果3", passive: "", mythicEffect: "ミシック効果3",money:"1000G", type: "mythic"},
  ];
  
  var legendaryitems = [
    { name: "メジャイソウルスティーラー", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "ケミテックピュートリファイアー", effect: "効果2", passive: "" ,money:"1000G", type: "legendary"},
    { name: "フローウォータースタッフ", effect: "効果3", passive: "" ,money:"1000G", type: "legendary"},
    { name: "アーデントセンサー", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "ジークコンバージェンス", effect: "効果2", passive: "" ,money:"1000G", type: "legendary"},
    { name: "騎士の誓い", effect: "効果3", passive: "" ,money:"1000G", type: "legendary"},
    { name: "帝国の指令", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "リデンプション", effect: "効果2", passive: "" ,money:"1000G", type: "legendary"},
    { name: "ミカエルの祝福", effect: "効果3", passive: "" ,money:"1000G", type: "legendary"},
    { name: "アンブラルグレイブ", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "ビジラントワードストーン", effect: "効果2", passive: "" ,money:"1000G", type: "legendary"},
    { name: "アビサルマスク", effect: "効果3", passive: "" ,money:"1000G", type: "legendary"},
    { name: "アナセマチェイン", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "冬の訪れ", effect: "効果2", passive: "" ,money:"1000G", type: "legendary"},
    { name: "バンシーヴェール", effect: "効果3", passive: "" ,money:"1000G", type: "legendary"},
    { name: "リーライクリスタルセプター", effect: "効果2", passive: "" ,money:"1000G", type: "legendary"},
    { name: "毒蛇の牙", effect: "効果3", passive: "" ,money:"1000G", type: "legendary"},
    { name: "フローズンハート", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "ソーンメイル", effect: "効果2", passive: "" ,money:"1000G", type: "legendary"},
    { name: "ランデュインオーメン", effect: "効果3", passive: "" ,money:"1000G", type: "legendary"},
    { name: "サンファイアイージス", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "ヴォイドスタッフ", effect: "効果2", passive: "" ,money:"1000G", type: "legendary"},
    { name: "ルナーンハリケーン", effect: "効果3", passive: "" ,money:"1000G", type: "legendary"},
    { name: "ファントムダンサー", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "マルモティウスの胃袋", effect: "効果2", passive: "" ,money:"1000G", type: "legendary"},
    { name: "ケミテックチェーンソード", effect: "効果3", passive: "" ,money:"1000G", type: "legendary"},
    { name: "ターボケミタンク", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "自然の力", effect: "効果2", passive: "" ,money:"1000G", type: "legendary"},
    { name: "マナムネ", effect: "効果3", passive: "" ,money:"1000G", type: "legendary"},
    { name: "ナイトエッジ", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "エッセンスリーバー", effect: "効果2", passive: "" ,money:"1000G", type: "legendary"},
    { name: "スピリットビサージュ", effect: "効果3", passive: "" ,money:"1000G", type: "legendary"},
    { name: "デッドマンプレート", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "アークエンジェルスタッフ", effect: "効果2", passive: "" ,money:"1000G", type: "legendary"},
    { name: "コズミックドライブ", effect: "効果3", passive: "" ,money:"1000G", type: "legendary"},
    { name: "ホライゾンフォーカス", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "シャドウフレイム", effect: "効果2", passive: "" ,money:"1000G", type: "legendary"},
    { name: "モレロノミコン", effect: "効果3", passive: "" ,money:"1000G", type: "legendary"},
    { name: "リッチベイン", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "ゾーニャの砂時計", effect: "効果2", passive: "" ,money:"1000G", type: "legendary"},
    { name: "悪魔の抱擁", effect: "効果3", passive: "" ,money:"1000G", type: "legendary"},
    { name: "コレクター", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "アクシオムアーク", effect: "効果2", passive: "" ,money:"1000G", type: "legendary"},
    { name: "プローラークロウ", effect: "効果3", passive: "" ,money:"1000G", type: "legendary"},
    { name: "スタティックシヴ", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "クラーケンスレイヤー", effect: "効果2", passive: "" ,money:"1000G", type: "legendary"},
    { name: "ストームレイザー", effect: "効果3", passive: "" ,money:"1000G", type: "legendary"},
    { name: "ラピッドファイアキャノン", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "イモータルシールドボウ", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "マーキュリアルシミター", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "モータルリマインダー", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "ドミニクリガード", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "ハルブレイカー", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "ガーディアンエンジェル", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "シルバーミアの夜明け", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "ワーモグアーマー", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "ステラックの篭手", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "ブラッククリーバー", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "ナッシャートゥース", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "ウィッツエンド", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "セリルダの怨恨", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "ガーゴイルストーンプレート", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "ルインドキングブレード", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "ショウジンの矛", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "デスダンス", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "タイタンハイドラ", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "ブラッドサースター", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "ラヴァナスハイドラ", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
    { name: "ラバドンデスキャップ", effect: "効果1", passive: "効果" ,money:"1000G", type: "legendary"},
  ];
  
  var epicitems = [
    { name: "リカーブボウ", effect: "効果1", passive: "効果" ,money:"1000G", type: "epic"},
    { name: "キルヒアイスシャード", effect: "効果2", passive: "" ,money:"1000G", type: "epic"},
    { name: "忘却のオーブ", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "フォビドゥンアイドル", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "エクスキューショナーコーリング", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "キンドルジェム", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "チェインベスト", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "ブランブルベスト", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "クリスタルブレーザー", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "翼のムーンプレート", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "エーテルウィスプ", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "グレイシャルバックラー", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "フィンディッシュの古書", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "ヴァンパイアセプター", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "ネガトロンクローク", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "ジャイアントベルト", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "バンドルグラスの鏡", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "祝福の聖杯", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "シーカーアームガード", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "ヴァ―ダントバリア", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "ワーデンメイル", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "バミシンダー", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "ヘクステックオルタネーター", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "生命泉のペンダント", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "ロストチャプター", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "枯死の宝石", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "ジール", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "ハースバウンドアックス", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "セレイテッドダーク", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "アイアンスパイクウィップ", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "コールフィールドウォーハンマー", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "ファージ", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "ウォッチフルワードストーン", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "レイジナイフ", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "ティアマト", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "イージスの盾", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "スペクターカウル", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "久遠のカタリスト", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "リーチングリア", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "ヌーンクィヴァー", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "へクスドリンカー", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "クイックシルバーサッシュ", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
    { name: "ラストウィスパー", effect: "効果3", passive: "" ,money:"1000G", type: "epic"},
  ];
  
  var basicitems = [
    { name: "フェアリーチャーム", effect: "効果1", passive: "効果" ,money:"1000G", type: "basic"},
    { name: "ダガー", effect: "効果2", passive: "" ,money:"1000G", type: "basic"},
    { name: "クロースアーマー", effect: "効果3", passive: "" ,money:"1000G", type: "basic"},
    { name: "再生の珠", effect: "効果3", passive: "" ,money:"1000G", type: "basic"},
    { name: "サファイアクリスタル", effect: "効果3", passive: "" ,money:"1000G", type: "basic"},
    { name: "ロングソード", effect: "効果3", passive: "" ,money:"1000G", type: "basic"},
    { name: "ルビークリスタル", effect: "効果3", passive: "" ,money:"1000G", type: "basic"},
    { name: "増魔の書", effect: "効果3", passive: "" ,money:"1000G", type: "basic"},
    { name: "ヌルマジックマント", effect: "効果3", passive: "" ,money:"1000G", type: "basic"},
    { name: "アジリティクローク", effect: "効果3", passive: "" ,money:"1000G", type: "basic"},
    { name: "シーン", effect: "効果3", passive: "" ,money:"1000G", type: "basic"},
    { name: "ストップウォッチ", effect: "効果3", passive: "" ,money:"1000G", type: "basic"},
    { name: "ブラスティックワンド", effect: "効果3", passive: "" ,money:"1000G", type: "basic"},
    { name: "ピッケル", effect: "効果3", passive: "" ,money:"1000G", type: "basic"},
    { name: "ムダニデカイロッド", effect: "効果3", passive: "" ,money:"1000G", type: "basic"},
    { name: "B.F.ソード", effect: "効果3", passive: "" ,money:"1000G", type: "basic"},
  ];
  
  var starteritems = [
    { name: "ダークシール", effect: "効果1", passive: "効果" ,money:"1000G", type: "starter"},
    { name: "女神の涙", effect: "効果2", passive: "" ,money:"1000G", type: "starter"},
    { name: "ドランリング", effect: "効果3", passive: "" ,money:"1000G", type: "starter"},
    { name: "スペルシーフエッジ", effect: "効果3", passive: "" ,money:"1000G", type: "starter"},
    { name: "レリックシールド", effect: "効果3", passive: "" ,money:"1000G", type: "starter"},
    { name: "霊者の鎌", effect: "効果3", passive: "" ,money:"1000G", type: "starter"},
    { name: "鋼のショルダーガード", effect: "効果3", passive: "" ,money:"1000G", type: "starter"},
    { name: "ドランブレード", effect: "効果3", passive: "" ,money:"1000G", type: "starter"},
    { name: "カル", effect: "効果3", passive: "" ,money:"1000G", type: "starter"},
    { name: "ドランシールド", effect: "効果3", passive: "" ,money:"1000G", type: "starter"},
    { name: "スコーチクロウの幼体", effect: "効果3", passive: "" ,money:"1000G", type: "starter"},
    { name: "ガストウォーカーの幼体", effect: "効果3", passive: "" ,money:"1000G", type: "starter"},
    { name: "モスストンパーの幼体", effect: "効果3", passive: "" ,money:"1000G", type: "starter"},
    
  ];

  var bootsitems = [
  { name: "ちょっと魔法のかかった靴", effect: "追加で移動速度を+10する", money:"時間経過で獲得", type: "boots"},
  { name: "ブーツ", effect: "移動速度+25", money:"300G", type: "boots"},
  { name: "スイフトネスブーツ", effect: "移動速度+60 スロウ効果を25％減少する", money:"900G", type: "boots"},
  { name: "アイオニアブーツ", effect: "移動速度+45スキルヘイスト+20", money:"950G", type: "boots"},
  { name: "モビリティブーツ", effect: "移動速度+25\n(非戦闘状態で5秒間いると移動速度が115に増加)", money:"1000G", type: "boots"},
  { name: "バーサーカーブーツ", effect: "移動速度+45 攻撃速度+35％", money:"1100G", type: "boots"},
  { name: "ソーサラーブーツ", effect: "移動速度+45 魔法防御貫通+18", money:"1100G", type: "boots"},
  { name: "プレートスチールキャップ", effect: "移動速度+45 物理防御+20", money:"1100G", type: "boots"},
  { name: "マーキュリーブーツ", effect: "移動速度+45 魔法防御+25 行動妨害耐性+30%", money:"1100G", type: "boots"},
];

var portionitems = [
{ name: "体力ポーション", effect: "15秒かけて体力を120回復する",money:"50G", type: "portion"},
{ name: "詰め替えポーション", effect: "1チャージを消費して体力を100回復する。2チャージ保持していてショップを訪れるとチャージが回復する。",money:"150G", type: "portion"},
{ name: "コラプトポーション", effect: "1チャージを消費して体力100とマナ75を12秒かけて回復する。さらに、12秒の間にAAと攻撃系スキルで敵に火をつけ15（マナを獲得できなかった場合20）の魔法ダメージを与える",money:"500G", type: "portion"},
];

var Worditems = [
{ name: "ステルスワード", effect: "味方に視界を与える。\nまた敵からはインビジブル状態となる。",money:"無料", type: "Word"},
{ name: "コントロールワード", effect: "味方に視界を与える。\nこの周辺にあるインビジブルの罠、カモフラージュの敵を可視化し、敵のステルスワードを可視化＆無効化する。",money:"75G", type: "Word"},
{ name: "オラクルレンズ", effect: "自分の周りをスキャンし範囲内の敵を見ることができる。敵の罠を可視化して一時敵に敵のステルスワードも可視化＆無効化する。",money:"無料", type: "Word"},
{ name: "フォーサイトオルタレーション", effect: "離れた位置に壊れやすい可視状態のワードを設置する。",money:"無料", type: "Word"},
];
